"""empty message

Revision ID: 024afc215b45
Revises: 7edcf537e48f
Create Date: 2023-07-22 16:50:15.639957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024afc215b45'
down_revision = '7edcf537e48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_formations',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('formation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formations.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'formation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_formations')
    # ### end Alembic commands ###
