"""empty message

Revision ID: 27829d14272e
Revises: 3d6e4454bf32
Create Date: 2023-07-22 10:30:36.738408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27829d14272e'
down_revision = '3d6e4454bf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('formation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'formations', ['formation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'formation_id')
    # ### end Alembic commands ###
